---
abstract: 'Obtain uploaded CPAN modules via a CPAN::Mini mirror'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-SmokeBox-Uploads-CPAN-Mini
no_index:
  directory:
    - inc
    - t
    - examples
requires:
  CPAN::Mini: 0.571
  CPAN::Mini::Devel: 0.02
  POE: 0.38
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
